// Uses VS code extension REST Client

POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "Bob",
    "email": "bob@email.com",
    "password": "supersecretpassword"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "bob@email.com",
    "password": "supersecretpassword"
}

###
GET http://localhost:5000/api/auth/refresh_token
